### ISSUE TITLE
How to visualize the final statistical data?

### ISSUE THREAD

**Issue by Avaniuniu** [GrotjahnLab/surface_morphometrics#20]
Hi ！ I am trying to run test data . After I ran the "morphometrics_stats.py", a .pkl file was generated. How should I open and visualize the data?

**Comment by bbarad** [comment]
As mentioned in the readme, `morphometrics_stats.py` when run as a command just outputs a pkl file that makes loading large datasets easier. In order to generate statistics, you can use the functions within that script in concert with loading the pkl file (a function to do that is in the script as well!) to generate different quantifications. Ultimately, the quantifications that are useful depend on the scientific question. With that said, if you want the exact quantifications in the paper you can download the full dataset from [EMPIAR](https://www.ebi.ac.uk/empiar/EMPIAR-11370/) and then run the script `mitochondria_statistics.py`.

Here are some things from the readme you can try to get started with stats:

### Examples of generating statistics and plots:
* `python single_file_histogram.py filename.csv -n feature` will generate an area-weighted histogram for a feature of interest in a single tomogram. I am using a variant of this script to respond to reviews asking for more per-tomogram visualizations!
* `python single_file_2d.py filename.csv -n1 feature1 -n2 feature2` will generate a 2D histogram for 2 features of interest for a single surface.
* `mitochondria_statistics.py` shows analysis and comparison of multiple experiment objects for different sets of tomograms (grouped by treatment in this case). Every single plot and statistic in the preprint version of the paper gets generated by this script.
